# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 09:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hostel_name', models.CharField(max_length=100)),
                ('departure_date', models.DateField(default=datetime.date.today)),
                ('arrival_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
