# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
